item { 
	name:'object1'
	id:1
}
item { 
	name:'object2'
	id:2
}
item { 
	name:'object3'
	id:3
}
item { 
	name:'object4'
	id:4
}
item { 
	name:'object5'
	id:5
}
item { 
	name:'object6'
	id:6
}
item { 
	name:'object7'
	id:7
}
item { 
	name:'object8'
	id:8
}
item { 
	name:'object9'
	id:9
}
item { 
	name:'object10'
	id:10
}
item { 
	name:'object11'
	id:11
}
item { 
	name:'object12'
	id:12
}
item { 
	name:'object13'
	id:13
}
item { 
	name:'object14'
	id:14
}
item { 
	name:'object15'
	id:15
}
item { 
	name:'object16'
	id:16
}
item { 
	name:'object17'
	id:17
}
item { 
	name:'object18'
	id:18
}
item { 
	name:'object19'
	id:19
}
item { 
	name:'object20'
	id:20
}
item { 
	name:'object21'
	id:21
}
item { 
	name:'object22'
	id:22
}
item { 
	name:'object23'
	id:23
}
item { 
	name:'object24'
	id:24
}
item { 
	name:'object25'
	id:25
}
item { 
	name:'object26'
	id:26
}
item { 
	name:'object27'
	id:27
}
item { 
	name:'object28'
	id:28
}
item { 
	name:'object29'
	id:29
}
item { 
	name:'object30'
	id:30
}
item { 
	name:'object31'
	id:31
}
item { 
	name:'object32'
	id:32
}
item { 
	name:'object33'
	id:33
}
item { 
	name:'object34'
	id:34
}
item { 
	name:'object35'
	id:35
}
item { 
	name:'object36'
	id:36
}item { 
	name:'object37'
	id:37
}